#!/bin/bash

make
cd rw_dolomite
./../rwhet_exe > ../output.out <<!
# ./../rwhet_exe <<!
dolomite.dat
../rw.out
../part.out
!
tail -n 20 output.out

# make
# cd example_4
# ./../rwhet_exe > a.out <<!
# example4.dat
# ../rw.out
# ../part.out
# !
