#!/bin/bash

cd ..
make
cd example_4
./../rwhet_exe > ../4output.out <<!
# ./../rwhet_exe <<!
example4.dat
4rw.out
4part.out
!

# make
# cd example_4
# ./../rwhet_exe > a.out <<!
# example4.dat
# ../rw.out
# ../part.out
# !
