#!/bin/bash

make
# ./adre_exe 2> a.err
./adre_exe > a.out 2> a.err
python plotting/plot_data.py time_concs.txt 0

# gfortran -c ADRE_mod.f90
# gfortran -o trans_exe test_trans.f90 ADRE_mod.f90
# ./trans_exe > a.out 2>&1
